version: 1.0.{build}
image:
- Visual Studio 2019
- Visual Studio 2022
configuration: Release
platform: Any CPU
init:
- git config --global core.autocrlf true
before_build:
- echo /restore /bl >> msbuild.rsp
build:
  verbosity: minimal
test_script:
- ps: |
    if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2019") {
      $integrationTestAssembly = "Tvl.VisualStudio.JustMyCodeToggle.IntegrationTests.14\bin\$env:CONFIGURATION\net46\Tvl.VisualStudio.JustMyCodeToggle.IntegrationTests.14.dll"
    } elseif ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq "Visual Studio 2022") {
      $integrationTestAssembly = "Tvl.VisualStudio.JustMyCodeToggle.IntegrationTests.17\bin\$env:CONFIGURATION\net472\Tvl.VisualStudio.JustMyCodeToggle.IntegrationTests.17.dll"
    } else {
      throw "Unsupported image: $env:APPVEYOR_BUILD_WORKER_IMAGE"
    }

    $xunitConsole = "$env:USERPROFILE\.nuget\packages\xunit.runner.console\2.4.1\tools\net472\xunit.console.x86.exe"
    $testResultsDirectory = "TestResults"
    $testResultsFile = "$testResultsDirectory\$($env:APPVEYOR_BUILD_WORKER_IMAGE -replace '[^A-Za-z0-9_.-]', '-')-xunit.log"
    New-Item -ItemType Directory -Force -Path $testResultsDirectory | Out-Null

    & $xunitConsole $integrationTestAssembly -noshadow -noautoreporters -verbose 2>&1 | Tee-Object -FilePath $testResultsFile
    $testExitCode = $LastExitCode

    if ($testExitCode -ne 0) { $host.SetShouldExit($testExitCode) }
artifacts:
- path: '**\*.vsix'
- path: 'TestResults\*.log'
  name: test results
- path: '\msbuild.binlog'
  name: build log
