// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Tvl.VisualStudio.JustMyCodeToggle
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidJustMyCodeTogglePackageString = "c86c0c68-5ff5-43af-8a60-54540cbea3e2";
        public static Guid guidJustMyCodeTogglePackage = new Guid(guidJustMyCodeTogglePackageString);

        public const string guidJustMyCodeTogglePackageCmdSetString = "4e7a4be2-f4dd-4cc1-a142-e23645e43ecd";
        public static Guid guidJustMyCodeTogglePackageCmdSet = new Guid(guidJustMyCodeTogglePackageCmdSetString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int JMCToolbarGroup = 0x1101;
        public const int JMCMenuController = 0x1102;
        public const int JMCNativeCodeBtn = 0x1103;
        public const int JMCJustMyCodeBtn = 0x1104;
        public const int JMCSymbolLoadBtn = 0x1105;
        public const int JMCDisableJitOptmizationsBtn = 0x1107;
    }
}
