// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Tvl.VisualStudio.JustMyCodeToggle
{
    internal sealed partial class Vsix
    {
        public const string Id = "Tvl.VisualStudio.JustMyCodeToggle.0E2F0645-E87E-433C-B82B-C89EAE52A0FD";
        public const string Name = "Just My Code Toggle";
        public const string Description = @"Adds the Just My Code command button to Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "1.4.6";
        public const string Author = "Sam Harwell";
        public const string Tags = "debugging, just my code";
        public const bool IsPreview = false;
    }
}
